### ISSUE TITLE
mobile sales problem

### ISSUE THREAD

**Issue by drawde123** [arclem888/arclemlan#13]
![IMG_20210711_193454](https://user-images.githubusercontent.com/87084451/125193238-fdb1a800-e27d-11eb-9d1a-e6015d1158e8.jpg)
paano ma fix yung date

**Comment by ardzky** [comment]
Saan po makadownload ng arclem wifi manager? Wala sa playstore.

**Comment by arclem888** [comment]
please use the web portal instead for arclem lan. https://arclemwifi.com
