### ISSUE TITLE
bugs/error on credit

### ISSUE THREAD

**Issue by Redosendo** [arclem888/arclemlan#14]
https://www.youtube.com/watch?v=-2HDpZddSyQ

ito yung issue ko sa arclem. if mag hulog si costumer (ex. 1 piso) pero di pindutin ang generate code at hayaan lang ang timer ni system na matapos di mag genarate sa sales ang hinulog ni costumer (note: newly connect po yung device ni tomer hindi para mag extend time) at maiiwan sa system ang credits na hinulog ng costumer. kung may another new costumer na mag hulog (ex. 5 pisos) (codeless) dun mag dagdag ang naiwan na credit (1 piso + 5 pisos na hinulog nya) sa system at kung hindi rin pindutin ni tomer ang genarate code at ipa tapos din ang counter time ng system maiiwan uli (naging 6 pisos) ang credit na hinulog ni tomer plus yung credit sa system na naiwan bago sya nag hulog hangang lumaki ang credit. at lahat na yung hindi pumapasok sa sales hangang may tomer na mag hulog at pumindot ng generate code saka pa mag genarate sa sales ang masaklap every costumer na maghulog after nung 1st na di nag pindut ng genarate ng code ay lumalaki yung time (1 piso + 5 pisos and so on).

I've try default config ng arclem (OCI) at own config (not OCI) same issue parin po

hardware used:
mikrotik hEX Gr3 version 6.47.10
Arclem Lan Software version 4.0.10
Ruijie EW1200G-PRO
nag try din ako ng AP Comfast ew71 but same issue

sana ma resolve na to na issue,
thanks and more power Arclem Team

**Comment by arclem888** [comment]
naka connect ba sa lan3 ung arclem lan sir? naka reset ba lahat tapos nag oci kayo? pasend din po dito yng logs ng mikrotik kasi di ko mareplicate.  gumagana kasi sa akin.
https://youtu.be/Gu5pWZieK3Q

**Comment by Redosendo** [comment]
> naka connect ba sa lan3 ung arclem lan sir? naka reset ba lahat tapos nag oci kayo? pasend din po dito yng logs ng mikrotik kasi di ko mareplicate. gumagana kasi sa akin.
> https://youtu.be/Gu5pWZieK3Q

yes sir
lan 1 ISP
lan 2 laptop
lan3 arclem lan
lan 4 AP

hEX Gr3 din po ba sang hardware mo sir in this testing

**Comment by Redosendo** [comment]
![2021-07-13](https://user-images.githubusercontent.com/86934971/125379527-4030cd00-e3c3-11eb-8a7a-0afe5658f9d7.png)

**Comment by Redosendo** [comment]
> naka connect ba sa lan3 ung arclem lan sir? naka reset ba lahat tapos nag oci kayo? pasend din po dito yng logs ng mikrotik kasi di ko mareplicate. gumagana kasi sa akin.
> https://youtu.be/Gu5pWZieK3Q

sir nag downgrade ako ng software 4.0.8 pero 4.0.10 parin na uploader ang gamit ko nawala po yung issue sa credit yun nga lang wala akong monitoring sa sales

**Comment by froias16** [comment]
I second this issue... but this looks to be an intermittent bug. Kaya di mareplicate.

Sir Redosendo, naka-tick ba login by MAC-Cookie sayo? Yun ang last na ginawa ko then this happened. Piso lang hulog, abot 2 days... abot pa sa 3rd phone yung credit.

**Comment by froias16** [comment]
Here's my log file, started 20:26
20:26:49 dhcp,info dhcpserverhs assigned 10.10.10.119 to C0:2E:25:E7:1F:9D 
20:26:55 dhcp,info dhcpserverhs deassigned 10.10.10.119 from C0:2E:25:E7:1F:9D 
20:26:55 dhcp,info dhcpserverhs assigned 10.10.10.119 to C0:2E:25:E7:1F:9D 
20:27:27 script,error script error: no such item 
20:27:34 dhcp,info dhcpserverhs assigned 10.10.10.118 to B4:CD:27:66:EB:D4 
20:27:49 script,error script error: no such item 
20:27:49 script,error script error: no such item 
20:27:50 script,error script error: no such item 
20:27:53 script,error script error: no such item 
20:27:53 script,error script error: no such item 
20:27:53 script,error script error: no such item 
20:27:55 script,error script error: no such item 
20:27:55 script,error script error: no such item 
20:27:56 script,error script error: no such item 
20:27:57 system,info hotspot user 629456 added by arca8032a627a70 
20:27:58 script,error script error: no such item 
20:27:59 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:27:59 hotspot,info,debug 629456 (10.10.10.119): trying to log in by http-chap 
20:27:59 hotspot,account,info,debug 629456 (10.10.10.119): logged in 
20:28:00 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:00 system,info new script scheduled 
20:28:00 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:28:00 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:00 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:28:01 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:01 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:28:02 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:02 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:28:02 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:20 interface,info ether3 link down 
20:28:21 interface,info ether3 link up (speed 100M, full duplex) 
20:28:21 dhcp,info dhcpserverhs deassigned 10.10.10.252 from A8:03:2A:62:7A:73 
20:28:21 dhcp,info dhcpserverhs assigned 10.10.10.252 to A8:03:2A:62:7A:73 
20:28:26 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:28:27 system,info hotspot walled-garden rule changed by arca8032a627a70 
20:28:28 system,info hotspot ip binding rule changed by arca8032a627a70 
20:28:32 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:28:40 system,info hotspot server profile default changed by admin 
20:28:40 info fetch: file "public/a8032a627a70.txt" downloaded 
20:28:49 system,info hotspot server profile hsprof1 changed by admin 
20:28:50 script,error script error: no such item 
20:28:54 dhcp,info dhcpserverhs deassigned 10.10.10.120 from 82:25:95:8B:C3:A1 
20:29:00 info fetch: file "public/a8032a627a70.txt" downloaded 
20:29:39 dhcp,info dhcpserverhs deassigned 10.10.10.231 from 2A:75:90:BE:75:08 
20:33:29 dhcp,info dhcpserverhs assigned 10.10.10.179 to 32:FD:5B:C4:7D:38 
20:34:15 dhcp,info dhcpserverhs deassigned 10.10.10.199 from C2:12:86:DC:EB:BD 
20:35:39 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
20:37:09 script,error script error: no such item 
20:37:09 script,error script error: no such item 
20:37:23 script,error script error: no such item 
20:37:24 script,error script error: no such item 
20:37:24 script,error script error: no such item 
20:37:27 script,error script error: no such item 
20:37:27 script,error script error: no such item 
20:37:28 script,error script error: no such item 
20:37:34 dhcp,info dhcpserverhs deassigned 10.10.10.118 from B4:CD:27:66:EB:D4 
20:37:34 script,error script error: no such item 
20:37:35 script,error script error: no such item 
20:37:35 script,error script error: no such item 
20:37:38 script,error script error: no such item 
20:37:39 script,error script error: no such item 
20:37:39 script,error script error: no such item 
20:37:47 system,info hotspot user 629516 added by arca8032a627a70 
20:37:48 script,error script error: no such item 
20:37:49 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:37:49 hotspot,info,debug 629516 (10.10.10.229): trying to log in by http-chap 
20:37:50 hotspot,info,debug 629516 (10.10.10.229): login failed: no chap for http-chap login method 
20:37:50 hotspot,account,info,debug 629516 (10.10.10.229): logged in 
20:37:51 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:37:51 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:37:51 system,info new script scheduled 
20:37:52 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:37:52 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:37:52 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:37:52 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:37:53 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:37:53 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:37:54 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:38:11 interface,info ether3 link down 
20:38:13 dhcp,info dhcpserverhs deassigned 10.10.10.252 from A8:03:2A:62:7A:73 
20:38:13 dhcp,info dhcpserverhs assigned 10.10.10.252 to A8:03:2A:62:7A:73 
20:38:13 interface,info ether3 link up (speed 100M, full duplex) 
20:38:19 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:38:20 system,info hotspot walled-garden rule changed by arca8032a627a70 
20:38:20 system,info hotspot ip binding rule changed by arca8032a627a70 
20:38:24 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:38:31 info fetch: file "public/a8032a627a70.txt" downloaded 
20:38:35 script,error script error: no such item 
20:38:42 info fetch: file "public/a8032a627a70.txt" downloaded 
20:38:51 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
20:38:52 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
20:42:45 hotspot,info,debug 627657 (10.10.10.232): logged out: keepalive timeout 
20:43:29 dhcp,info dhcpserverhs deassigned 10.10.10.179 from 32:FD:5B:C4:7D:38 
20:44:41 dhcp,info dhcpserverhs assigned 10.10.10.220 to 18:31:BF:DB:4E:13 
20:45:25 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
20:45:25 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
20:45:36 dhcp,info dhcpserverhs assigned 10.10.10.235 to EC:56:23:2B:A9:15 
20:46:07 hotspot,info,debug abc125 (10.10.10.235): trying to log in by http-chap 
20:46:09 hotspot,info,debug abc125 (10.10.10.235): login failed: invalid username or password 
20:46:13 script,error script error: no such item 
20:46:14 script,error script error: no such item 
20:46:43 script,error script error: no such item 
20:46:46 system,info hotspot user 629562 added by arca8032a627a70 
20:46:47 script,error script error: no such item 
20:46:48 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:46:48 hotspot,info,debug 629562 (10.10.10.235): trying to log in by http-chap 
20:46:49 hotspot,account,info,debug 629562 (10.10.10.235): logged in 
20:46:49 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:46:49 system,info new script scheduled 
20:46:49 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:46:50 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:46:50 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:46:51 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:46:51 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:46:54 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:46:54 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:46:55 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:47:12 interface,info ether3 link down 
20:47:14 interface,info ether3 link up (speed 100M, full duplex) 
20:47:17 dhcp,info dhcpserverhs deassigned 10.10.10.252 from A8:03:2A:62:7A:73 
20:47:18 dhcp,info dhcpserverhs assigned 10.10.10.252 to A8:03:2A:62:7A:73 
20:47:20 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:47:21 system,info hotspot walled-garden rule changed by arca8032a627a70 
20:47:21 system,info hotspot ip binding rule changed by arca8032a627a70 
20:47:25 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:47:33 info fetch: file "public/a8032a627a70.txt" downloaded 
20:47:35 script,error script error: no such item 
20:47:37 info fetch: file "public/a8032a627a70.txt" downloaded 
20:47:40 system,info hotspot server profile hsprof1 changed by admin 
20:47:46 system,info hotspot server profile default changed by admin 
20:48:21 dhcp,info dhcpserverhs assigned 10.10.10.196 to 5C:1C:B9:E1:F9:2B 
20:48:31 dhcp,info dhcpserverhs deassigned 10.10.10.232 from B4:9C:DF:2B:AF:94 
20:48:34 script,error script error: no such item 
20:48:34 script,error script error: no such item 
20:48:53 script,error script error: no such item 
20:48:54 system,info hotspot user 629575 added by arca8032a627a70 
20:48:55 script,error script error: no such item 
20:48:56 hotspot,info,debug 629575 (10.10.10.196): trying to log in by http-chap 
20:48:56 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:48:56 hotspot,account,info,debug 629575 (10.10.10.196): logged in 
20:48:57 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:48:57 system,info new script scheduled 
20:48:57 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:49:00 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:49:00 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:49:00 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:49:01 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:49:01 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:49:01 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:49:02 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:49:20 interface,info ether3 link down 
20:49:21 interface,info ether3 link up (speed 100M, full duplex) 
20:49:22 dhcp,info dhcpserverhs deassigned 10.10.10.252 from A8:03:2A:62:7A:73 
20:49:22 dhcp,info dhcpserverhs assigned 10.10.10.252 to A8:03:2A:62:7A:73 
20:49:27 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:49:28 system,info hotspot walled-garden rule changed by arca8032a627a70 
20:49:28 system,info hotspot ip binding rule changed by arca8032a627a70 
20:49:32 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:49:37 dhcp,info dhcpserverhs deassigned 10.10.10.248 from 60:21:01:79:42:F4 
20:49:37 dhcp,info dhcpserverhs assigned 10.10.10.248 to 60:21:01:79:42:F4 
20:49:46 info fetch: file "public/a8032a627a70.txt" downloaded 
20:49:51 script,error script error: no such item 
20:49:56 info fetch: file "public/a8032a627a70.txt" downloaded 
20:50:06 script,error script error: no such item 
20:50:06 script,error script error: no such item 
20:50:21 script,error script error: no such item 
20:50:24 system,info hotspot user 629575 changed by arca8032a627a70 
20:50:24 hotspot,info,debug 629575 (10.10.10.196): logged out: admin reset 
20:50:25 hotspot,info,debug 629575 (10.10.10.196): trying to log in by cookie 
20:50:25 script,error script error: no such item 
20:50:25 hotspot,account,info,debug 629575 (10.10.10.196): logged in 
20:50:26 system,info changed scheduled script settings 
20:50:36 script,error script error: no such item 
20:51:33 interface,info ether3 link down 
20:51:45 interface,info ether3 link up (speed 100M, full duplex) 
20:51:48 dhcp,info dhcpserverhs deassigned 10.10.10.252 from A8:03:2A:62:7A:73 
20:51:48 dhcp,info dhcpserverhs assigned 10.10.10.252 to A8:03:2A:62:7A:73 
20:51:51 system,info,account user arca8032a627a70 logged in from 10.10.10.252 via api 
20:51:52 system,info hotspot walled-garden rule changed by arca8032a627a70 
20:51:52 system,info hotspot ip binding rule changed by arca8032a627a70 
20:52:04 info fetch: file "public/a8032a627a70.txt" downloaded 
20:52:06 system,info,account user arca8032a627a70 logged out from 10.10.10.252 via api 
20:52:08 script,error script error: no such item 
20:52:24 script,error script error: no such item 
20:52:38 hotspot,info,debug 620956 (10.10.10.212): logged out: admin reset 
20:52:38 hotspot,error,info,debug 620956 (10.10.10.212): stop accounting: local user not found 
20:52:38 system,info item removed 
20:52:38 system,info hotspot user 620956 removed 
20:52:39 system,info script removed from scheduler 
20:52:52 script,error script error: no such item 
20:53:04 system,info hotspot user 629562 changed by arca8032a627a70 
20:53:04 hotspot,info,debug 629562 (10.10.10.235): logged out: admin reset 
20:53:05 script,error script error: no such item 
20:53:15 hotspot,info,debug 629562 (10.10.10.235): trying to log in by cookie 
20:53:16 hotspot,account,info,debug 629562 (10.10.10.235): logged in 
20:53:22 system,info changed scheduled script settings 
20:53:26 script,error script error: no such item 
20:54:41 dhcp,info dhcpserverhs deassigned 10.10.10.220 from 18:31:BF:DB:4E:13 
20:56:43 system,info,account user admin logged out from 192.168.99.82 via winbox 
21:00:34 script,error script error: no such item 
21:00:53 script,error script error: no such item 
21:00:54 script,error script error: no such item 
21:00:54 script,error script error: no such item 
21:00:58 script,error script error: no such item 
21:00:58 script,error script error: no such item 
21:00:59 script,error script error: no such item 
21:01:01 script,error script error: no such item 
21:01:06 script,error script error: no such item 
21:01:06 script,error script error: no such item 
21:01:07 script,error script error: no such item 
21:01:08 hotspot,info,debug 622088 (10.10.10.248): trying to log in by cookie 
21:01:09 hotspot,account,info,debug 622088 (10.10.10.248): logged in 
21:01:10 script,error script error: no such item 
21:01:14 script,error script error: no such item 
21:01:17 script,error script error: no such item 
21:01:45 script,error script error: no such item 
21:01:50 system,info hotspot user 629654 added by arca8032a627a70 
21:01:51 script,error script error: no such item 
21:01:52 hotspot,info,debug 629654 (10.10.10.212): trying to log in by http-chap 
21:01:53 hotspot,account,info,debug 629654 (10.10.10.212): logged in 
21:01:53 system,info new script scheduled 
21:02:03 script,error script error: no such item 
21:04:40 dhcp,info dhcpserverhs assigned 10.10.10.247 to 9C:0C:DF:B0:B6:55 
21:05:25 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:05:30 hotspot,info,debug 629516 (10.10.10.229): logged out: lost dhcp lease 
21:06:28 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:07:24 hotspot,info,debug 629562 (10.10.10.235): logged out: keepalive timeout 
21:08:26 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:08:26 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:10:24 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:10:26 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:10:33 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:10:33 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:10:48 dhcp,info dhcpserverhs deassigned 10.10.10.235 from EC:56:23:2B:A9:15 
21:12:00 info fetch: file "public/a8032a627a70.txt" downloaded 
21:13:22 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:13:22 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:13:55 dhcp,info dhcpserverhs assigned 10.10.10.231 to 2A:75:90:BE:75:08 
21:14:40 dhcp,info dhcpserverhs deassigned 10.10.10.247 from 9C:0C:DF:B0:B6:55 
21:14:44 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:14:44 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:15:32 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:15:33 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:16:07 hotspot,info,debug 629516 (10.10.10.229): trying to log in by http-chap 
21:16:08 hotspot,account,info,debug 629516 (10.10.10.229): logged in 
21:16:44 system,info,account user admin logged in from 192.168.99.82 via winbox 
21:17:11 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:17:11 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:18:19 dhcp,info dhcpserverhs deassigned 10.10.10.248 from 60:21:01:79:42:F4 
21:18:24 hotspot,info,debug 622088 (10.10.10.248): logged out: lost dhcp lease 
21:18:38 dhcp,info dhcpserverhs assigned 10.10.10.248 to 60:21:01:79:42:F4 
21:18:44 dhcp,info dhcpserverhs deassigned 10.10.10.248 from 60:21:01:79:42:F4 
21:18:44 dhcp,info dhcpserverhs assigned 10.10.10.248 to 60:21:01:79:42:F4 
21:22:06 info fetch: file "public/a8032a627a70.txt" downloaded 
21:23:55 dhcp,info dhcpserverhs deassigned 10.10.10.231 from 2A:75:90:BE:75:08 
21:24:35 hotspot,info,debug 622088 (10.10.10.248): trying to log in by cookie 
21:24:35 hotspot,account,info,debug 622088 (10.10.10.248): logged in 
21:26:03 dhcp,info dhcpserverhs assigned 10.10.10.117 to 48:83:B4:37:F3:A3 
21:26:17 dhcp,info dhcpserverhs deassigned 10.10.10.117 from 48:83:B4:37:F3:A3 
21:26:28 dhcp,info dhcpserverhs assigned 10.10.10.117 to 48:83:B4:37:F3:A3 
21:28:29 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:28:29 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:29:29 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:29:29 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:32:15 info fetch: file "public/a8032a627a70.txt" downloaded 
21:33:29 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:33:29 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:33:58 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:34:01 dhcp,info dhcpserverhs assigned 10.10.10.229 to 50:3C:EA:65:F6:89 
21:34:36 dhcp,info dhcpserverhs assigned 10.10.10.116 to D0:16:B4:E6:15:F7 
21:36:28 dhcp,info dhcpserverhs deassigned 10.10.10.117 from 48:83:B4:37:F3:A3 
21:37:30 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:37:30 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:38:03 hotspot,info,debug 629516 (10.10.10.229): logged out: keepalive timeout 
21:42:20 info fetch: file "public/a8032a627a70.txt" downloaded 
21:42:41 dhcp,info dhcpserverhs assigned 10.10.10.235 to EC:56:23:2B:A9:15 
21:43:21 hotspot,info,debug 629575 (10.10.10.196): logged out: keepalive timeout 
21:43:29 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:43:29 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:43:40 dhcp,info dhcpserverhs assigned 10.10.10.115 to 3C:CD:5D:69:0A:3E 
21:44:01 dhcp,info dhcpserverhs deassigned 10.10.10.229 from 50:3C:EA:65:F6:89 
21:44:36 dhcp,info dhcpserverhs deassigned 10.10.10.116 from D0:16:B4:E6:15:F7 
21:44:59 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:44:59 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:45:47 system,info changed email settings by admin 
21:46:12 dhcp,info dhcpserverhs assigned 10.10.10.215 to 9C:0C:DF:1C:B5:37 
21:46:32 e-mail,info sent <Test Arclem MT> to: froias76@gmail.com  
21:48:48 dhcp,info dhcpserverhs deassigned 10.10.10.196 from 5C:1C:B9:E1:F9:2B 
21:48:59 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:48:59 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:50:05 dhcp,info dhcpserverhs deassigned 10.10.10.170 from 0C:EC:84:D2:6E:D0 
21:50:05 dhcp,info dhcpserverhs assigned 10.10.10.170 to 0C:EC:84:D2:6E:D0 
21:50:09 system,info new script scheduled by admin 
21:50:42 system,info changed scheduled script settings by admin

**Comment by Redosendo** [comment]
resolve na po yung issue, salamat po sir Arclem.... ayaw pala ng MT sa mahabang variable sa device name
