### ISSUE TITLE
error/unable to update v4.0.10

### ISSUE THREAD

**Issue by webnetvpn** [arclem888/arclemlan#15]
https://user-images.githubusercontent.com/57629047/125535694-1d533aa0-1458-4cf8-9ee6-82160f470a76.mp4

hardware used:
mikrotik haplite version 6.46.6

sana ma resolve na to na issue,
thanks and more power Arclem Team

**Comment by arclem888** [comment]
add 8.8.8.8 to dns server on mikrotik.  dapat may hdd space din sa mikrotik ng 2mb

**Comment by webnetvpn** [comment]
5.9mb pa naman po space at nilagyan ko na dns server 8.8.8.8 error parin po

**Comment by arclem888** [comment]
fixed on v4.1
