### ISSUE TITLE
Please add in portal free trial

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#17]
Thanks

**Comment by foxnet8** [comment]
insert mo b4 </form> nang "KB"/"UP"
$(if trial == 'yes')
<button class="buttona" onclick="location.href = '$(link-login-only)?dst=$(link-orig-esc)&amp;username=T-$(mac-esc)';"><i class="icon icon-thumbs-up">&#128073;&#127996; </i><small style="color:rgb(255, 117, 140);font-size:18px;font-weight:bold">10 mins FREE WiFi</small><i class="icon icon-thumbs-up">&#128072;&#127995; </i></button>
				$(else)
<button class="buttona3"><i class="icon icon-block">&#128683; </i><small style="font-size:18px;font-weight:bold">"FREE Trial Expired" <i class="icon icon-block">&#128683; </i></small></button>
				$(endif)
MarkAndrew :)

**Comment by arclem888** [comment]
added in v4.1
