### ISSUE TITLE
Enhancement: Codegen, start scheduler when code is used/ log in

### ISSUE THREAD

**Issue by froias16** [arclem888/arclemlan#21]
For codegen, can we have the scheduler start when user logs in using the code? That way user can buy codes for later use? like when we manually create users directly in MT. User is created with uptime limits and all but not in Scheduler yet. Mapupunta lang yung user code sa scheduler pag ginamit na to login.

Thanks.

**Comment by sutil101** [comment]
yes, nag run na yung time sa codegen kahit di pa nagamit. v4

**Comment by froias16** [comment]
this is addressed and closed. Thanks sir Arclem
