### ISSUE TITLE
enhancement  / upgrade v3 

### ISSUE THREAD

**Issue by sutil101** [arclem888/arclemlan#22]
possible na yung some feature ng v4 ay ma-incorporate sa v3.

1. insert coin - cancel button or auto cancel if cancel sa insert coin portal.
2. de-active other user if sabay nakapag insert coin.
3. validity.
4. OTA sa website.
5. and simplify the uploader. user friendly. 
6. sa v3. pwede ba na may option yung public folder pwede sa disk (sa mga naka mt na may sd card / usb port.

**Comment by arclem888** [comment]
sa september / october sir naka schedule

**Comment by arclem888** [comment]
already available in current version
