### ISSUE TITLE
issue on generating code

### ISSUE THREAD

**Issue by MarkLesterBus** [arclem888/arclemlan#24]
nag try ako mag insert coin, ok naman yung online check, kaso pag mag generate na, naka lagay "Please wait....", nag connect na yung phone ko please wait parin, until mag reboot si arclem tsaka lang mawawala at babalik sa dati.

**Comment by arclem888** [comment]
check mo logs ng mikrotik  sir  then paste mo dito

**Comment by MarkLesterBus** [comment]
![image](https://user-images.githubusercontent.com/83324648/130173708-855e027d-5e58-4c0b-b6cd-6b18cae7846a.png)

**Comment by arclem888** [comment]
pacheck yung hotspot server mo sa uploader baka naka hotspot12 . pwede mo
rin ilagay ng all para pwede sa lahat ng hotspot server

**Comment by MarkLesterBus** [comment]
hotspot1 po naka lagay, e try ko pong lagyan ng all.

**Comment by MarkLesterBus** [comment]
Sir ok naman po yung pag generate ng code uisng button, kaso pag sa portal po may error, pati po pag extend ng time may error din po.

**Comment by MarkLesterBus** [comment]
Sir ok naman po yung pag generate ng code uisng button, kaso pag sa portal po may error, pati po pag extend ng time may error din po.

**Comment by MarkLesterBus** [comment]
na gegenirate naman po yung code may isang error lang po na script.
![Capture](https://user-images.githubusercontent.com/83324648/130175689-8365a9a9-59c9-4d1b-babb-6ffd2166cb4a.PNG)
ito po yung pag nag extend ako ng time sa voucher ko.
![Capture2](https://user-images.githubusercontent.com/83324648/130175693-dabbd14b-8045-481c-ae26-778f286ebd71.PNG)

**Comment by arclem888** [comment]
paste mo daw dito sir ung may val na rsc sa folder ng mikrotik mo. 2 yun

**Comment by MarkLesterBus** [comment]
:global validity24a160c61414
:global inserted24a160c61414
:global timestr24a160c61414
:global profile24a160c61414
:global code24a160c61414
:global valfile24a160c61414
:global bytes24a160c61414

:local addscript ("{/ip hotspot cookie remove [find user=$code24a160c61414];/ip hotspot user remove [find name=$code24a160c61414];/ip hotspot active remove [find user=$code24a160c61414];/file remove $valfile24a160c61414 ;/system scheduler remove [find name=$code24a160c61414] }");
:local limituptime [/ip hotspot user get [find name=$code24a160c61414] limit-uptime ];
:local uptime [/ip hotspot user get [find name=$code24a160c61414] uptime ];
:if ($bytes24a160c61414 = "NA" ) do={
  :global timeleft ($limituptime - $uptime + $validity24a160c61414);

  :local sched [/system scheduler find name=$code24a160c61414];
  :if ($sched) do={:local lastuptime [:totime [/system scheduler get $sched comment]]; :if ($lastuptime != $limituptime ) do={/system scheduler set $sched interval=$timeleft comment=$limituptime}} else={/system scheduler add name=$code24a160c61414 interval=$timeleft on-event=$addscript comment=$limituptime};

} else={
  :global timeleft ($uptime + $validity24a160c61414);
  /system scheduler add name=$code24a160c61414 interval=$timeleft on-event=$addscript comment=$bytes24a160c61414
}

**Comment by arclem888** [comment]
screenshot mo daw ung sa scripts  environment

**Comment by MarkLesterBus** [comment]
![Capture22](https://user-images.githubusercontent.com/83324648/130177748-96d327a4-2294-4a79-aed1-0dbf2215d736.PNG)

**Comment by arclem888** [comment]
ano version ng mikritik os mo sir?

**Comment by arclem888** [comment]
version sir. paupdate nlang po muna sa stable na version. punta ka sa
system packages update

**Comment by MarkLesterBus** [comment]
6.48.3 updated napo

**Comment by MarkLesterBus** [comment]
ok na po, ang ginawa ko lang nag flash ako ng v4.0.8 na firmware, at ginamit ko na uploader ay 4.0.10.
working na lahat may ilang feature lang na wala sa uploader.

**Comment by arclem888** [comment]
cg sir thanks. check ko nalng muna ung sa 4.1
