### ISSUE TITLE
it this possible features?

### ISSUE THREAD

**Issue by evilcyberx** [arclem888/arclemlan#30]
disconect vendo and reconect vendo.. incase boss na nag maintenance or walang net para hindi mahulugan ng client ung vendo iwas reklamo.. posible ba ganito?

**Comment by adjieph** [comment]
Good day,
Saan i insert yung redirect link after successful login? 
Possible ba sa portal?
Ty.

**Comment by arclem888** [comment]
i disable mo lang ung account/user ng vendo sir sa mikrotik. pag nag error kasi ung login credentials ng vendo nag didisable un  sya.
