### ISSUE TITLE
Telegram on Arclem DIY LAN not working

### ISSUE THREAD

**Issue by jhnativi** [arclem888/arclemlan#31]
No response upon clicking Integrate Telegram on browser...

**Comment by jhe28** [comment]
ayaw po gumana ang telegram nag-update nmn po ako ng v9 pero hndi po nagconnect sa telegram

**Comment by jhe28** [comment]
failed to update po v7 to any version above v7..

**Comment by mcandres888** [comment]
sa web admin po ung telegram i setup sir. need nyo ilagay ung channel doon.
https://www.youtube.com/watch?v=YeHVTqII_5w

**Comment by arclem888** [comment]
sa web admin po ung telegram i setup sir. need nyo ilagay ung channel doon.
https://www.youtube.com/watch?v=YeHVTqII_5w
