### ISSUE TITLE
No Device Name in List of DIY LAN but with Name in Dashboard

### ISSUE THREAD

**Issue by iverol88** [arclem888/arclemlan#32]
issue: 
why does my DIY LAN have a name in the Dashboard, but in the list of Arclem Lan DIY Devices there is no name? :)

**Comment by arclem888** [comment]
nasa web po sir sa edit banda. meron dun naka lagay na name. medyo na separate kasi ung sa naming sa vendo at sa naming sa dashboard. edit mo nalng sir at ipareha ung name.
