### ISSUE TITLE
Scipt error on log file: failure connection timeout

### ISSUE THREAD

**Issue by webnetvpn** [arclem888/arclemlan#33]
After mag hulog at generate code si tomer yan po error at hindi nagkacount sa sales report.. ngayon ko lng na encounter september 5, 2021 naka v4.2.0 arclem device po ako.
![image](https://user-images.githubusercontent.com/57629047/132110839-54abb455-ce58-4126-b386-2f53ae40deb8.png)
MT logs message: Sep/05/2021 07:24:51 memory script, error  script error: failure: ssl connection error: internal error (6)
Sep/05/2021 07:24:51 memory script, error  script error: failure: connection timeout

**Comment by arclem888** [comment]
pasend sir ng version ng router os sir. di ko kasi to na encouter sa stable version

**Comment by arclem888** [comment]
check mo ung dns sir. dapat naka set sa 1.1.1.1 or 8.8.8.8
