### ISSUE TITLE
Error creating code contact owner

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#34]
as title says error creating code 

each time we insert coin it is unable to generate code but will accept insert coin and will add up to the credit found sa LCD 

done reboot and reset device still no go... vendo down again :( 

firmware version v4.2 
hex gr3 firmware 6.48.3

https://youtu.be/XaEQS_7usCQ

**Comment by arclem888** [comment]
check mo ung sa config mo sir. baka ung hotspot server is not the same. try
mo palitan nlang ng all. may namali lang yan sa configuration
