### ISSUE TITLE
hinde mag update ang date sa daily income monitoring

### ISSUE THREAD

**Issue by ianguatno** [arclem888/arclemlan#36]
hinde mag update ang date sa daily incom
![241710437_580538783071857_2878318813037171705_n](https://user-images.githubusercontent.com/90603105/133044062-56bc252a-49d2-4c3b-ba7e-37781d6052d7.jpg)
e monitoring..

**Comment by drawde123** [comment]
same problem sa akin sir

**Comment by arclem888** [comment]
ok na to sir nag update na ako sa web

**Comment by ianguatno** [comment]
tnx po sir....👍👍👍
