### ISSUE TITLE
Enhance feature

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#38]
Remote reboot for arclem lan kit... Included sa OTA update onnthe website like auto reboot after updating

**Comment by foxnet8** [comment]
Mag lagay ka nalang nang wifi smart plug yan ang nilagay ko sa vendo ko pwede e sched ang noff n on Outlets remain off after a power outage to save energy;save on your electric bills and extend product life- It lets you control devices connected to the Smart Plugs just using your voice.
-Create customized schedules when you need the WiFi wall outlet power devices on and off, a perfect outlet timer for your home.
-Use your smartphone or tablet to control your devices with the "smart life" app through any Wi-Fi network connection; ideal for hard-to-reach appliances & devices without ON/OFF switches- Save energy;save on your electric bills and extend product life.

**Comment by arclem888** [comment]
yes sir mas ok po ung naka different module ung sa pag on off. meron din po reboot ung sa device pero every 10 hours sya na naka standby at walng gumagamit. nag try din ako ng para sa remote reboot kaso medyo makukulangan na ako sa resources ng device. kaya mas better po ung isang suggestion.

**Comment by arclem888** [comment]
pero after updating. nagrereboot naman un ng kusa
