### ISSUE TITLE
Unable to do OTA update from 4.07 to 4.09 or updated versions

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#4]
I was working with Mark via anydesk unable to update my arclem lan 
using mikrotik Hex gr3
tried updating from 4.07 to 4.08 to no avail 
tried 4.07 to 4.09 still no go...

tried using upload na oldbuild and ung latest wala pa rin. 

nasayang lng OCI ko and pa load kay sir mark.

sana ma fix..

PS: salamat sir mark sa pag troubleshoot. 

di problema ang network kasi ge check na namin ni sir mark ok naman ... ayaw lng mag update tlga.

**Comment by arclem888** [comment]
add nyo po sa mikrotik. sa ip/dns  server 8.8.8.8
make sure nyo din na hdd space is 2mb

**Comment by Brooks08** [comment]
yes sir meron po dns attach ko po photo for reference. 
![dns](https://user-images.githubusercontent.com/86872170/124354094-186d8800-dbbf-11eb-9df4-7cac3a2acdf7.jpg)

tapos may ext sd card na rin po ng 16gb nilagay ko and na format na din ng ext extension using mikrotik as required by sir Mark during troubleshooting.

![image](https://user-images.githubusercontent.com/86872170/124354121-3e932800-dbbf-11eb-8f93-ae5619da0e6d.png)

sana makatulong po pag fix ng issue TIA

**Comment by arclem888** [comment]
pa check din sir system resources  ung available disk space

**Comment by Brooks08** [comment]
eto po sir 

![image](https://user-images.githubusercontent.com/86872170/124355256-0f7fb500-dbc5-11eb-9ec8-71bcdd510637.png)

**Comment by Brooks08** [comment]
resolve na po to... share ko lng for others to learn from my experience. 

ang sakin kasi na dahilan ng cause ng error is ung ISP ko is connected to a Newifi router na nag hahandle ng isa ko pang network tapos from NEWIFI connected kay mikrotik then going to arclem Lan... ito ang dahilan bakit nag eeror sa log file nya ng unable to resolve hostname...kaya ganito ang network ko kasi may mga client na connected sa Newifi at may online class na di ko ma disconnect agad... so pa ra ma resolve ... 

dapat ang topology ng network ay ganito para mag work ang OTA update...

ISP to Mikrotik to arclem lan ... then follow na lng ung OTA update guide ni sir Arclem sa youtube... 

sana maka tulong sa mga nag ka problema...
