### ISSUE TITLE
DIY LAN POWER SUPPLY

### ISSUE THREAD

**Issue by kmlProjects** [arclem888/arclemlan#40]
Sir please help me, 4 kits of diy lan binili ko, okay na ako sa nodemcu, nkabili n po ng license. Ngastart na ako configure ng isang mt as partner ng kit.

Ang problem po is if ung kit using usb lan cord as power source connected sa laptop, uokay ung lcd but yung coin sot is hndm prang hnd kaya ng usb power chord from laptop supplayan ang buong circuit including coin slot.

Now, kpag tinagGal ko n ung usb chord from laptop at replaced by Power Adapter 12v-3A na binili rin sa shopee sa arclem store, biglang prang dark blue n lng ung lcd but ung coin slot umilaw na. 

I'm confused if san ako my mali sa ginawa ko. Hindi ko pa inuumpisahan ung tatlong natira kasi doubt ako na baka pareho mangyari eh. 

Please help me po to identify the possible cause of this, pra ma take note po at ma apply sa next set up.

https://user-images.githubusercontent.com/61592029/137585300-c4e382a9-23e8-4f10-a2df-7225fd14e323.mp4

**Comment by arclem888** [comment]
try mo sir hindi lipat. full off mo muna lahat. tapos gamitin mo ung
supply. check mo din sa arduino at custom board sa baba baka may nagdikit.
