### ISSUE TITLE
Arclem LAN + V3 Tutorial

### ISSUE THREAD

**Issue by miraizkie** [arclem888/arclemlan#41]
From V3, pinalitan ko ng LAN ung setup ko. Ngayon gusto ko sana iadd yung V3 as my subvendo, sana meron tutorial kng paano. Sinubukan ko but laging nag eeror config ung LAN. Thanks!

**Comment by arclem888** [comment]
upgrade nlang po to v4 ung mga v4 na devices sir. para pwede sila maka sabay sa setup na bago
