### ISSUE TITLE
Web sales

### ISSUE THREAD

**Issue by Abbie-P1sowifi** [arclem888/arclemlan#44]
Created code didnt seen in web sale portal.

**Comment by Abbie-P1sowifi** [comment]
@arclem888 created code didnt seen in web sales portal

**Comment by Abbie-P1sowifi** [comment]
Paki fix naman kasi hindi ko ma monitor ang sales. Hindi kasi napasok sa web port ang mga generated codes.

**Comment by arclem888** [comment]
ok na to sir
