### ISSUE TITLE
Issue sa diy v3 codeless

### ISSUE THREAD

**Issue by adminbako** [arclem888/arclemlan#45]
Pag insertcoin ni client at pag generate sa cp di pumasok code already expired na daw peru meron sa mikrotik

**Comment by adminbako** [comment]
Marami po ang code na di nagamit sa mikrotik

**Comment by arclem888** [comment]
pa update nalng sa v4 sir

**Comment by adminbako** [comment]
update ako from v3 to v4 ayaw mag generate and upload settings sir nka sunod nmn ako sa vid tutorial mu po
