### ISSUE TITLE
LAN v4.3.1

### ISSUE THREAD

**Issue by zerorelov** [arclem888/arclemlan#48]
autocredit issue. Padagdag nang padagdag yung naiiwang credit..
example may naghulog ng 30pesos, after makalogin ni 30pesos,
error na si lanv4, then autorestart,
then, di pa naghuhulog next customer, may 30pesos agad...
if mag hulog si customer#2 ng 5pesos, magiging 35pesos
customer#3 10pesos, magiging 45pesos.

Nakailang bago nako ng rates, ang di ko pa lang nata-try is ireset yung lanv4
nasa linang kasi, di pako makapunta pero pinapa-turn off turn on ko sa tito ko (reset narin ba matawag yun?). 

Ineedit ko nalang kada hulog kasi alam ko naman kapag autocredit yung device..

ang weird kasi kapag piso, 10pesos, 7pesos di nag eerror vendo. Pag dating ng 25pesos pataas dun ako nag error

update: nalalaman ko autocredit once yung validity hindi kumakagat, example 30pesos dapat validity nito ay 1d, 
sa halip na 1d, 1m lumalabas sa validity. dun ko nalalaman yung trigger, bukod sa error yung vendo, yung validity kapag "1m" alam ko na autocredit
![image](https://user-images.githubusercontent.com/94780099/142755630-ec546875-b091-4e07-b74a-11e0cd6eb515.png)

**Comment by arclem888** [comment]
pa attach ng video sir  para m re create natin.
