### ISSUE TITLE
Nawawalang time ni customer 

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#5]
scenario....

nag hulog ng pang 1 day na rate... 

tapos si mer nag ka internet na xempre di pa nya matapos or may iba pa xang gagawin ... so mag disconnect xa sa wifi ng vendo...

maya maya ... since 1 day pa ang hinulog nya... pag reconnect nya sa portal wala ng time si customer....

0 or disconnected na xa....

--- happen on 4 phones sa bahay as test
using arclem lan with Hex gr3 mikrotik via OCI no other changes made since default tlga xa kakareset...
version is 4.07 --- due to unable to update firmware na din...

ps: cant deploy vendo if ganito... uulanin tau ng reklamo sa mga customer sana ma fix TIA

**Comment by arclem888** [comment]
ongoing yung testing ko nito sir.  may iimplement ako na bagong flow dun sa validity  na part. baka next week may resolution na.

**Comment by Brooks08** [comment]
ayon ohh salamat sir at napansin hehe

**Comment by arclem888** [comment]
fixed on version 4.0.10
