### ISSUE TITLE
Possible new feauture? 

### ISSUE THREAD

**Issue by evilcyberx** [arclem888/arclemlan#59]
nakita ko lang sa ibang vendo. meron silang midnight ligth posible ba ito boss arclem? na if mag 6 pm na eh mag aactivate ung kuryente ng 12 v para bumukas ung ilaw? tapos pag 6 am na auto matic cut power? [https://www.mediafire.com/view/3rn3heoy7lvc6oc/wwwaaa.jpg/file](url)

**Comment by sunnyber17** [comment]
motion sensor  lang sakin sir

**Comment by mcandres888** [comment]
mas ok ung light sensor sir nalang sir or motion sensor para bawas process po sa ating device
