### ISSUE TITLE
Files cleaning and RemoteWinBox

### ISSUE THREAD

**Issue by elbertsss** [arclem888/arclemlan#64]
boss arclem pwede din bang palinis nung uploader? May files kasi na nauupload sa mikrotik na hindi naman ginagamit, sayang sa space ng device.

And pwede din kaya maintegrate sa uploader yung remotewinbox? Para pwede mag upload ng hotspot or rates remotely using remotewinbox.

More power po thanks.

**Comment by arclem888** [comment]
added remote winbox capability on version 4.5.0
