### ISSUE TITLE
No internet after clean up script run 

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#70]
As title says boss 
after mag run ang clean up script na didisable ung tracking and set to NO

di na xa bumabalik sa YES causing no internet connection 

sana maayos sa next update TIA 

Herbie :)

**Comment by arclem888** [comment]
disable mo nlang muna ung sa clean up script sir for now.

**Comment by arclem888** [comment]
meron na sa bagong uploader na disable ung sa firewall cleanup
