### ISSUE TITLE
Night Light

### ISSUE THREAD

**Issue by evilcyberx** [arclem888/arclemlan#75]
boss arclem pwede mo bang idagdag to...  hindi mo na kasi ako kinakausap.. allan to.. lagyan mo sana dun sa board mo na may output na 12v.. pag nag 6 pm mag kakaroon ng kuryente.. para sana sa mga vendo na gusto mag lagay ng ilaw para na seset pwede i set kung ano oras ubbukas at mamatay..  sana ma gets mo

**Comment by arclem888** [comment]
sir gamit nlang po kayo ng device para mag on gamit ung ldr. meron naman pong separate na device para doon. tsaka medyo mura lang un :) lagay lang ako sa shopee ng ganun.
