### ISSUE TITLE
suggestions: Portal

### ISSUE THREAD

**Issue by Brooks08** [arclem888/arclemlan#77]
First of all thank you sa new portal design na dinagdag sa 4.4 onwards na update. 

Sana maka add ng dark theme na portal and other designs na din para may pag pipiliian 

sana pwed din dag dagan instead sa tawk chat may link na lng sa FB ng owner para e click ni customer at e message sa messenger for concern ... 

sa tawk kasi need pa ng email at di madaling e monitor as mag login pa ang owner sa tawk para makita...

or if pwed telegram like ung parang sa existing ngaun na pag hulog ni customer mag message sa telegram 

ung chat kung pwed ba via telegram na lng para pag message mag pop out agad sa telegram ni owner...

un lng po salamat :) 

Herbie

**Comment by arclem888** [comment]
pag facebook chat sir, di sya basta basta ilagay. kasi need mo pa ng domain name nun at server para ma authenticate ng FB.
