### ISSUE TITLE
Validity Issues

### ISSUE THREAD

**Issue by jimbsvan** [arclem888/arclemlan#78]
Ang nangyari kasi sa validity hindi sya ma extend pero yong time na extend. Example if si client naghulog ng 10 pesos tapos ang validity non is example 2 days lang. Kahit na mag extend kapa ng time para hindi mag expire yong na avail mong codes yong validity ay hindi nag extend pero yong time nag extend. After don sa validity ng una mong hulog yon ang susundin ng system to delete the codes or voucher kahit na naka extend kana ng time na dapat na extend din yong validity.

Eto lang yong problema: ang validity ay dapat madagdagan if si client ng extend ng time. Another good option para dito is pwede tayo maka create ng account exclusive para don sa mga supportive client natin na pwede tayo maka gawa ng account tapos yong pwede natin malagyan ng oras na gusto nila. Para bang may ownership na din sila sa e avail nila na voucher pero pang lifetime na username and password at yong ang maging voucher nila. Pag malapit na maubos yong time nila pwede sila mag extend time na laman ng account nila.

**Comment by arclem888** [comment]
meron na po to s bagong update v4.8.0
