### ISSUE TITLE
nagbago ang validity after update

### ISSUE THREAD

**Issue by Ellandsky** [arclem888/arclemlan#8]
nag update ako sa 4.0.9 sa lahat ng subvendo ko. ng na update na c version 4.0.9 pag naghulog sila ng 1 peso or 5pesos ang validity nya nasa 1day.  bakit kaya ganun sir. gusto ko sana ung 4.0.9 dahil sa sales report. at telegram

**Comment by arclem888** [comment]
fixed on version 4.0.10
