### ISSUE TITLE
code prefix

### ISSUE THREAD

**Issue by PotatoPum** [arclem888/arclemlan#80]
pag nag lagayn ako ng input sa "code prefix" for identification sana kung saang vendo sila nag hulog... pag nag extend time ang client...  naka lagay  "time extended" kaagad kahit di pa nakahulog ang client at ang indication sa LCD screen naman ay naka insert coin parin..salamat sir arclem..sana matugunan ang bug na to..b.t.w.. 4.5.0 na uploader ang ginagamit ko..

**Comment by arclem888** [comment]
dapat naka lower case ung code prefix sir.
